name: Devsecops test CI

on:
  pull_request:
    branches:
      - master

jobs:

  test_command:
    name: Devsecops test CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Exec shell
      run:
        id
        ls -lah
        echo "Ganda Himawan is here" 